stages:
  - testing
  - logs

test_job:
  stage: testing
  script:
  - dotnet restore
  - dotnet test
  when: manual
  tags: 
    - my-ubuntu
  only:
    - dev
  
gather_log_job:
  stage: logs
  script:
  - docker logs selenoid &> logs.log
  - docker logs selenoid &> logs_today_temp.log && cat logs_today_temp.log | grep ""$(date ""+%Y/%m/%d"")"" > logs_today.log
  artifacts:
     paths:
     - logs.log
     - logs_today.log
  when: on_failure
  tags: 
    - my-ubuntu
  only:
    - dev
