stages:
  - before_test
  - testing
  - logs

before_testing_job:
  stage: before_test
  script:
  - echo "hi"


test_job:
  stage: testing
  script:
  - dotnet restore
  - dotnet test
  
gather_log_job:
  stage: logs
  script:
  - docker logs selenoid &> logs.log
  artifacts:
     paths:
     - logs.log
