stages:
  - testing
  - logs

test_job:
  stage: testing
  script:
  - dotnet restore
  - dotnet test
  when: manual
  tags: 
    - my-ubuntu
  only:
    - dev
  
gather_log_job:
  stage: logs
  script:
  - docker logs selenoid &> container_logs.log
  - docker logs selenoid &> logs_today_temp.log && cat logs_today_temp.log | grep ""$(date ""+%Y/%m/%d"")"" > container_logs_today.log
  - tar -cf browser_logs.tar /home/gitlab-runner/selenoid/logs
  artifacts:
     paths:
     - container_logs.log
     - container_logs_today.log
     - browser_logs.tar
  when: on_failure
  tags: 
    - my-ubuntu
  only:
    - dev
